on: 
  workflow_dispatch:
  schedule:
    - cron: "25,55 * * * *" # Every 30m

name: build-perf-experiment

jobs:
  ci:
    runs-on:
      - namespace-profile-default
    steps:
      - uses: actions/checkout@v4
      - run: |
          dd if=/dev/urandom of=perf_experiment/bigfile bs=1M count=2048 status=progress
      - run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ env.NSC_CONTAINER_REGISTRY }}/image:amd64 \
            --push \
            ./perf_experiment