on: 
  workflow_dispatch:
  schedule:
    - cron: "25,55 * * * *" # Every 30m

name: build-perf-load-experiment

jobs:
  load-wo-cache:
    runs-on:
      - namespace-profile-default
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker buildx build \
            --platform linux/amd64 \
            --load \
            ./perf_experiment_load
  load-w-cache:
    runs-on:
      - namespace-profile-containerdcache
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker buildx build \
            --platform linux/amd64 \
            --load \
            ./perf_experiment_load