on: [workflow_dispatch]

name: simple

jobs:
  ci:
    runs-on:
      - namespace-profile-my-larger-runner
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          # cat ~/.docker/config.json
          uname -a
          locale
          docker version
          docker buildx version
          cd /cache && df -h .

      - uses: actions/checkout@v3

      - run: |
          time docker pull ubuntu
