on: [workflow_dispatch]

name: simple

jobs:
  ci:
    runs-on:
      - namespace-profile-testing-cache
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          # cat ~/.docker/config.json
          uname -a
          locale
          docker version
          docker buildx version
          cd /cache && df -h .
      
      - name: ls root 
        run: |
          ls -lta /

      - name: Checkout with Namespace Git mirrors cache
        uses: namespacelabs/nscloud-checkout-action@v1
        with:
          fetch-depth: 0

      - run: |
          time docker pull ubuntu
