on: [push, workflow_dispatch]

name: ci

jobs:
  ci:
    runs-on: nscloud
    steps:
      - name: AWS CLI Version
        run: |
          aws --version
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          tags: user/app:latest
  in-container:
    runs-on: nscloud
    container:
      image: grafana/mimir-build-image:goupdate-751733fe1
    steps:
      - name: checkout
        uses: actions/checkout@v3
