on: [workflow_dispatch]

name: localcache

jobs:
  ci:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-8x16-with-cache
      - nscloud-cache-tag-simple
      - nscloud-cache-size-1gb
      - nscloud-exp-container-image-cache
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          # cat ~/.docker/config.json
          uname -a
          locale
          docker version
          docker buildx version
          cd /cache && df -h .
    
      - name: Cache Primes
        id: cache-primes
        uses: namespacelabs/nscloud-cache-action@aaf178a2ab85acb742a5912a75ed7a3d1865d338
        with:
          path: prime-numbers
          key: ${{ runner.os }}-primes
          local-cache: true
  
      - name: Generate Prime Numbers
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: echo "world" > prime-numbers/hello
  
      - name: Use Prime Numbers
        run: cat prime-numbers/hello
