on: [push, workflow_dispatch]

name: shared-daemon

jobs:
  ci:
    runs-on: nscloud
    steps:
      - name: Start nginx
        run: |
          docker run --network=host nginx -d
          docker ps
      - name: Poke nginx
        run: |
          curl http://localhost:80
