on: [workflow_dispatch]

name: simple

jobs:
  ci:
    runs-on:
      - nscloud-ubuntu-20.04-staging-amd64-4x16-with-cache
      - nscloud-cache-exp-do-not-commit
      - nscloud-cache-tag-test
      - nscloud-cache-size-50gb
    steps:
      - name: Env checks
        run: |
          # ulimit -a
          # aws --version
          # docker buildx ls 
          env
          # cat ~/.docker/config.json
          # uname -a
          # locale
          # docker version
          # docker buildx version
          # cd /cache && df -h .
          # node -v
      - run: gh version
      - run: ls -lta /usr
      - run: ls -lta /usr/share/dotnet
      - name: Test terraform
        run: |
          terraform version
      - name: Test brew
        run: |
          brew --version
          ls -lta /home/linuxbrew
      - name: Test aws cli and ssm plugin
        run: |
          aws --version
          session-manager-plugin

      - uses: actions/setup-dotnet@v4
        continue-on-error: true
        with:
          dotnet-version: 8.0.200
          cache: false
      - uses: actions/setup-dotnet@v3
        continue-on-error: true
        with:
          dotnet-version: 8.0.x
          cache: false

      - name: Breakpoint if tests failed
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 1h
          authorized-users: gmichelo  

  # custom-ns-image:
  #   runs-on: namespace-profile-custom-image
  #   steps:
  #     - name: Check if psql is installed
  #       run: |
  #         psql --version  
  
  ci-gh-runner:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Env checks
        run: |
          # ulimit -a
          # aws --version
          # docker buildx ls 
          env
          # cat ~/.docker/config.json
          # uname -a
          # locale
          # docker version
          # docker buildx version
      - run: ls -lta /usr
      - run: ls -lta /usr/share
      # - name: Test brew
      #   run: |
      #     brew --version
      #     ls -lta /home/linuxbrew
      - run: df -i
      - run: lsblk
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          cache: false

      - name: Breakpoint if tests failed
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 1h
          authorized-users: gmichelo  

