on: 
  workflow_dispatch:
  push:
  pull_request:

name: simple

env:
  WORKING_DIR: perf_experiment

jobs:
  ci-1:
    runs-on:
      - windows-2025
    # container:
    #   image: ubuntu
    #   # Privileged is needed for tailscale to work.
    #   options: >-
    #     --init
    #     --privileged

    # environment:
    #   name: Test
    steps:
      - name: Check if WSL is installed
        run: |
          if (Get-Command wsl -ErrorAction SilentlyContinue) {
            Write-Host "WSL is installed"
            wsl --list --verbose
          } else {
            Write-Host "WSL is not installed"
            exit 1
          }
        shell: pwsh
      - name: LS
        run: 
          ls -lta /home
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Checkout
      #   uses: namespacelabs/nscloud-checkout-action@v7
      #   with: 
      #     ref: gmichelo.NSL-1234.test-branch
      # # - uses: ruby/setup-ruby@v1
      # #   with:
      # #     ruby-version: '3.3'
      # #     bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      # - run: bundle exec rake
      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
      #     tags: user/app:latest
      # - run: |
      #    docker run --privileged --rm --ulimit rtprio=99 ubuntu bash -ic 'chrt -f 50 ls'
      # # - run: |
      # #     sudo go test -v ./internal/tracefs/...
      - name: Breakpoint if tests failed
        uses: namespacelabs/breakpoint-action@v0
        if: always()
        with:
          duration: 1h
          authorized-users: gmichelo,hugosantos
  ci:
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    runs-on:
      # - nscloud-ubuntu-24.04-amd64-4x16
      # - namespace-experiments:github.run-id=${{ github.run_id }};github.run-attempt=${{ github.run_attempt }};container.fix_fuse_perms
      - nscloud-ubuntu-22.04-amd64-8x32-with-cache
    # environment:
    #   name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Breakpoint if tests failed
        uses: namespacelabs/breakpoint-action@v0
        if: always()
        with:
          duration: 1h
          authorized-users: gmichelo,hugosantos

      

      - uses: snapcore/action-build@v1
      # - name: Test checkout of another private repository
      #   uses: namespacelabs/nscloud-checkout-action@HEAD
      #   with:
      #     repository: gmichelo-dev/runner-tool-cache
      #     token: ${{ secrets.CHECKOUT_PAT }} # `GH_PAT` is a secret that contains your PAT
      #     path: tools
      #     submodules: recursive
      #     persist-credentials: true

      # - name: Test checkout of another private repository
      #   uses: namespacelabs/nscloud-checkout-action@HEAD
      #   with:
      #     repository: gmichelo-dev/test-private
      #     token: ${{ secrets.CHECKOUT_PAT }} # `GH_PAT` is a secret that contains your PAT
      #     path: test-private
      #     submodules: recursive
      #     persist-credentials: true
    
      - run: pwd
      - run: getent passwd
      - run: getent group
      - run: gh version
      - run: ls -lta /home
      - run: ls -lta /usr
      - run: ls -lta /usr/share/dotnet
      - run: sudo cat /etc/sudoers
      - name: Test terraform
        run: |
          terraform version
  
      - name: Test aws cli and ssm plugin
        run: |
          aws --version
          session-manager-plugin

      - uses: actions/setup-dotnet@v4
        continue-on-error: true
        with:
          dotnet-version: 8.0.200
          cache: false
      - uses: actions/setup-dotnet@v3
        continue-on-error: true
        with:
          dotnet-version: 8.0.x
          cache: false

      - name: Test brew
        run: |
          brew --version
          ls -lta /home/linuxbrew
          brew update --preinstall

      

  # custom-ns-image:
  #   runs-on: namespace-profile-custom-image
  #   steps:
  #     - name: Check if psql is installed
  #       run: |
  #         psql --version  
  
  ci-gh-runner:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout foundation
        uses: actions/checkout@v4
        with:
          repository: namespacelabs/foundation
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
          cache: false
      - name: Build nsc
        run: go build -v -o /tmp/nsc ./cmd/nsc
      - uses: actions/checkout@v4
      - uses: namespacelabs/nscloud-setup@v0
      - run: |
          /tmp/nsc build  .

      - uses: namespacelabs/breakpoint-action@v0
        if: always()
        with:
          duration: 1h
          authorized-users: gmichelo 
     

