on: [push, workflow_dispatch]

name: simple

jobs:
  ci:
    runs-on: nscloud
    steps:
      - name: Env checks
        run: |
          aws --version
          docker buildx ls 
          env
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: user/app:latest
