on: [workflow_dispatch]

name: simple

jobs:
  ci:
    runs-on:
      - nscloud-ubuntu-20.04-amd64-4x16
    steps:
      # - name: Breakpoint if tests failed
      #   uses: namespacelabs/breakpoint-action@v0
      #   with:
      #     duration: 1h
      #     authorized-users: gmichelo  
      # - name: Env checks
      #   run: |
      #     ulimit -a
      #     aws --version
      #     docker buildx ls 
      #     env
      #     # cat ~/.docker/config.json
      #     uname -a
      #     locale
      #     docker version
      #     docker buildx version
      #     cd /cache && df -h .
      #     node -v

      - run: df -i
      - run: lsblk

  custom-ns-image:
    runs-on: namespace-profile-custom-image
    steps:
      - name: Check if psql is installed
        run: |
          psql --version  
  
  ci-gh-runner:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # - name: Env checks
      #   run: |
      #     ulimit -a
      #     aws --version
      #     docker buildx ls 
      #     env
      #     cat ~/.docker/config.json
      #     uname -a
      #     locale
      #     docker version
      #     docker buildx version
      - run: df -i
      - run: lsblk

