on: [push, workflow_dispatch]

name: simple

jobs:
  ci:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-8x16-with-cache
      - nscloud-cache-tag-simple
      - nscloud-cache-size-1gb
      - nscloud-exp-container-image-cache
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          # cat ~/.docker/config.json
          uname -a
          locale
          docker version
          docker buildx version
          cd /cache && df -h .

      - uses: actions/checkout@v3

      - name: Configure buildx
        uses: namespacelabs/nscloud-setup-buildx-action@4c37ef8c6de2b360badda38fc29eec7a9f257ad3
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: nscr.io/01gr1g2rpb7ahzddy3f227exq9/testdocker:latest
  ci-gh-runner:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          cat ~/.docker/config.json
          uname -a
          locale
          docker version
          docker buildx version

      - name: Configure access to Namespace
        uses: namespacelabs/nscloud-setup@v0
      - name: Configure buildx
        uses: namespacelabs/nscloud-setup-buildx-action@4c37ef8c6de2b360badda38fc29eec7a9f257ad3
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: nscr.io/01gr1g2rpb7ahzddy3f227exq9/testdocker:latest
