on: [workflow_dispatch]

name: simple

jobs:
  ci:
    runs-on:
      - nscloud-ubuntu-22.04-arm64-4x16-with-cache
      - nscloud-cache-tag-cache-go
      - nscloud-cache-size-25gb
      - nscloud-git-mirror-40gb
      - nscloud-exp-container-image-cache
      - nscloud-exp-runner-tool-cache-10gb
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          # cat ~/.docker/config.json
          uname -a
          locale
          docker version
          docker buildx version
          cd /cache && df -h .
          node -v

      - name: Check if psql is installed
        run: |
          psql --version   

      - run: pwd
      - uses: actions/checkout@v3
      - run: pwd

      - name: Configure buildx
        uses: namespacelabs/nscloud-setup-buildx-action@4c37ef8c6de2b360badda38fc29eec7a9f257ad3
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: nscr.io/01gr1g2rpb7ahzddy3f227exq9/testdocker:latest

  custom-ns-image:
    runs-on: namespace-profile-custom-image
    steps:
      - name: Check if psql is installed
        run: |
          psql --version  
  
  ci-gh-runner:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          cat ~/.docker/config.json
          uname -a
          locale
          docker version
          docker buildx version
      - name: Breakpoint if tests failed
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: gmichelo
      - name: Configure access to Namespace
        uses: namespacelabs/nscloud-setup@v0
      - name: Configure buildx
        uses: namespacelabs/nscloud-setup-buildx-action@4c37ef8c6de2b360badda38fc29eec7a9f257ad3
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: nscr.io/01gr1g2rpb7ahzddy3f227exq9/testdocker:latest
