on: [workflow_dispatch]

name: simple

jobs:
  ci-1:
    runs-on:
      - namespace-profile-default
      # - nscloud-exp-features:use-node=ext-fsn1-dc20-2374834
    # environment:
    #   name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml up -d
  ci:
    defaults:
      run:
        working-directory: perf_experiment
    runs-on:
      - nscloud-ubuntu-24.04-amd64-4x16
      - namespace-experiments:github.run-id=${{ github.run_id }};github.run-attempt=${{ github.run_attempt }};container.fix_fuse_perms
    # environment:
    #   name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          echo "pwd: $(pwd)"
          env
      - name: env from typescript
        run: |
          import * as exec from "@actions/exec";
          const { stdout } = await exec.getExecOutput(`pwd`, [], {
            silent: !core.isDebug(),
          })
          console.log(stdout.trim());
      - name: Breakpoint if tests failed
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 1h
          authorized-users: gmichelo 
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.12' 
      # - run: python --version
      # - run: pip --version
      # - name: Breakpoint if tests failed
      #   uses: namespacelabs/breakpoint-action@v0
      #   if: always()
      #   with:
      #     duration: 1h
      #     authorized-users: gmichelo, hugosantos
      - name: Env checks
        run: |
          # ulimit -a
          # aws --version
          docker buildx ls 
          docker version
          docker buildx version
          env
          sudo apt-get update -y 
          sudo apt-get install dnsutils -y
          dig rendezvous.namespace.so
          # cat ~/.docker/config.json
          # uname -a
          # locale
          
          # cd /cache && df -h .
          # node -v
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ghostty-org/ghostty

      - name: Breakpoint if tests failed
        uses: namespacelabs/breakpoint-action@v0
        if: always()
        with:
          duration: 1h
          authorized-users: gmichelo,hugosantos

      - uses: snapcore/action-build@v1
      # - name: Test checkout of another private repository
      #   uses: namespacelabs/nscloud-checkout-action@HEAD
      #   with:
      #     repository: gmichelo-dev/runner-tool-cache
      #     token: ${{ secrets.CHECKOUT_PAT }} # `GH_PAT` is a secret that contains your PAT
      #     path: tools
      #     submodules: recursive
      #     persist-credentials: true

      # - name: Test checkout of another private repository
      #   uses: namespacelabs/nscloud-checkout-action@HEAD
      #   with:
      #     repository: gmichelo-dev/test-private
      #     token: ${{ secrets.CHECKOUT_PAT }} # `GH_PAT` is a secret that contains your PAT
      #     path: test-private
      #     submodules: recursive
      #     persist-credentials: true
    
      - run: pwd
      - run: getent passwd
      - run: getent group
      - run: gh version
      - run: ls -lta /home
      - run: ls -lta /usr
      - run: ls -lta /usr/share/dotnet
      - run: sudo cat /etc/sudoers
      - name: Test terraform
        run: |
          terraform version
  
      - name: Test aws cli and ssm plugin
        run: |
          aws --version
          session-manager-plugin

      - uses: actions/setup-dotnet@v4
        continue-on-error: true
        with:
          dotnet-version: 8.0.200
          cache: false
      - uses: actions/setup-dotnet@v3
        continue-on-error: true
        with:
          dotnet-version: 8.0.x
          cache: false

      - name: Test brew
        run: |
          brew --version
          ls -lta /home/linuxbrew
          brew update --preinstall

      

  # custom-ns-image:
  #   runs-on: namespace-profile-custom-image
  #   steps:
  #     - name: Check if psql is installed
  #       run: |
  #         psql --version  
  
  ci-gh-runner:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - run: uname -a
      - run: pwd
      - run: which kubectl
      - run: which helm
      - run: getent passwd
      - run: getent group
      - run: cat /etc/resolv.conf
      - name: Breakpoint if tests failed
        uses: namespacelabs/breakpoint-action@v0
        if: always()
        with:
          duration: 1h
          authorized-users: gmichelo 
      - name: Env checks
        run: |
          docker buildx ls 
          docker version
          docker buildx version
      - run: ls -lta /usr
      - run: ls -lta /home
      - run: ls -lta /usr/share
      - run: sudo cat /etc/sudoers
      - run: df -i
      - run: lsblk

      - name: Test checkout of another private repository
        uses: actions/checkout@v4
        with:
          repository: gmichelo-dev/runner-tool-cache
          token: ${{ secrets.CHECKOUT_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: tools
          submodules: recursive
          persist-credentials: true

      - name: Test checkout of another private repository
        uses: actions/checkout@v4
        with:
          repository: gmichelo-dev/test-private
          token: ${{ secrets.CHECKOUT_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: test-private
          submodules: recursive
          persist-credentials: true

      - name: Breakpoint if tests failed
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 1h
          authorized-users: gmichelo  

