on: [push, workflow_dispatch]

name: With Contatiner

jobs:
  with-container:
    runs-on: nscloud
    container:
      image: debian:bullseye
    steps:
      - name: checkout
        uses: actions/checkout@v3
